name: vikings_theme_demo
description: Flutter Vikings 2022 theme talk demo app
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=2.17.0 <3.0.0'
  # flutter: '>=3.1.0-0.0.pre.2199'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
