name: vikings_theme_demo
description: Flutter Vikings 2022 theme talk demo app
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
